apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: custom-store
spec:
  provider:
    webhooks:
      url: "http://web.prod-secret-store.svc.cluster.local/api/v1/secrets"
