apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test2-secret
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: custom-store          # references the ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: test2          
  data:
    - secretKey: password     
      remoteRef:
        key: test2              
