apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "0.9.19" # pin a stable version
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    createNamespace: true
  values:
    installCRDs: true  # install required CRDs during first install
    crds:
      createClusterSecretStore: true      # install ClusterSecretStore CRD
      createClusterExternalSecret: false  # disable cluster-level ExternalSecret
      createClusterPushSecret: false      # disable push secrets
    processClusterStore: true
    processClusterExternalSecret: false
    processClusterPushSecret: false
