apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod-secret-store
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      sourceRef:
        kind: GitRepository
        name: secret-store-git
        namespace: flux-system
  install:
    createNamespace: true
  values:
    appName: prod-secret-store

    image:
      repository: joehuangcoding/secret-store
      tag: "0.1.1"
      pullPolicy: IfNotPresent

    replicaCount: 1

    service:
      type: ClusterIP
      port: 80

    env:
      - name: NODE_ENV
        value: production

    configMap:
      enabled: true
      name: secret-store-config
      data:
        

    externalSecrets:
      enabled: false
