apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  interval: 5m
  releaseName: opentelemetry-collector
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      version: 0.73.1
  values:
    mode: deployment
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: false
      kubernetesAttributes:
        enabled: true
      kubernetesEvents:
        enabled: true
    resources:
      limits:
        cpu: 256m
        memory: 512Mi
    config:
      extensions:
        health_check:
          check_collector_pipeline:
            enabled: false
        basicauth/logs:
          client_auth:
            username: 1117173
            password: "glc_eyJvIjoiMTMzODAxOSIsIm4iOiJ0ZXN0LWdyYWZhbmEtZ3JhZmFuYWpoY29kaW5nIiwiayI6ImFPNFFRM1prODV5STBRTjU3ZDNqZVQxOCIsIm0iOnsiciI6InVzIn19"
        basicauth/metrics:
          client_auth:
            username: 2242991
            password: "glc_eyJvIjoiMTMzODAxOSIsIm4iOiJ0ZXN0LWdyYWZhbmEtZ3JhZmFuYWpoY29kaW5nIiwiayI6ImFPNFFRM1prODV5STBRTjU3ZDNqZVQxOCIsIm0iOnsiciI6InVzIn19"
        basicauth/traces:
          client_auth:
            username: 1111488
            password: "glc_eyJvIjoiMTMzODAxOSIsIm4iOiJ0ZXN0LWdyYWZhbmEtZ3JhZmFuYWpoY29kaW5nIiwiayI6ImFPNFFRM1prODV5STBRTjU3ZDNqZVQxOCIsIm0iOnsiciI6InVzIn19"
      service:
        pipelines:
          logs:
            receivers:
              - filelog
              - otlp
            processors:
              - memory_limiter
              - batch
              - k8sattributes/labels
              - resource/loki_add_hints
              - attributes/loki_add_hints
            exporters:
              - loki
              - debug/logs
          metrics:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - filter/ottl
              - transform
              - batch
            exporters:
              - prometheusremotewrite
              - debug/metrics
          traces:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp
              - debug/traces
        extensions:
          - basicauth/logs
          - basicauth/metrics
          - basicauth/traces
          - health_check
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318
              cors:
                allowed_origins:
                  - "http://*"
                  - "https://*"
      processors:
        memory_limiter:
          check_interval: 30s
          limit_percentage: 50
          spike_limit_percentage: 30
        filter/ottl:
          error_mode: ignore
          metrics:
            metric:
              - 'name == "queueSize"'
              - 'name == "rpc.server.duration"'
        transform:
          metric_statements:
            - context: metric
              statements:
                - set(description, "") where name == "queueSize"
                - set(description, "") where name == "rpc.server.duration"
                - set(description, "") where name == "http.client.duration"
        k8sattributes/labels:
          auth_type: "serviceAccount"
          passthrough: false
          pod_association:
            - sources:
              - from: resource_attribute
                name: k8s.pod.name
            - sources:
              - from: resource_attribute
                name: k8s.namespace.name
            - sources:
              - from: connection
          extract:
            metadata:
              - k8s.pod.name
              - k8s.container.name
              - k8s.deployment.name
              - k8s.node.name
              - k8s.namespace.name
              - k8s.pod.start_time
              - k8s.replicaset.name
              - k8s.daemonset.name
            labels:
              - tag_name: $$1
                key_regex: app.kubernetes.io/(.*)
                from: pod

        resource/loki_add_hints:
          attributes:
            - action: upsert
              key: k8s_cluster_name
              from_attribute: k8s.cluster.name
            - action: upsert
              key: k8s_namespace_name
              from_attribute: k8s.namespace.name
            - action: upsert
              key: k8s_container_name
              from_attribute: k8s.container.name
            - action: upsert
              key: k8s_deployment_name
              from_attribute: k8s.deployment.name
            - action: upsert
              key: k8s_node_name
              from_attribute: k8s.node.name
            - action: insert
              key: loki.resource.labels
              value: "\
                k8s_cluster_name,\
                k8s_namespace_name,\
                k8s_container_name,\
                k8s_node_name,\
                component,\
                instance,\
                name"

        attributes/loki_add_hints:
          actions:
            - action: upsert
              key: log_iostream
              from_attribute: log.iostream
            - action: insert
              key: loki.attribute.labels
              value: "log_iostream"
      exporters:
        loki:
          endpoint: https://logs-prod-026.grafana.net/loki/api/v1/push
          auth:
            authenticator: basicauth/logs
        prometheusremotewrite:
          resource_to_telemetry_conversion: 
            enabled: true
          endpoint: https://prometheus-prod-41-prod-au-southeast-1.grafana.net/api/prom/api/prom/push
          auth:
            authenticator: basicauth/metrics
        otlp:
          endpoint: tempo-prod-16-prod-au-southeast-1.grafana.net/tempo:443
          auth:
            authenticator: basicauth/traces
        debug/logs:
          verbosity: basic
        debug/metrics:
          verbosity: basic
        debug/traces:
          verbosity: basic
