apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: production-auth-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: custom-store
    kind: ClusterSecretStore
  target:
    name: ghcr-secret       # The Kubernetes Secret that will be created
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson   # Important for image pull secrets
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ printf \"%s:%s\" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: ghcrImagePullSecret   # Key in your secret store
        property: username
    - secretKey: password
      remoteRef:
        key: ghcrImagePullSecret
        property: password