apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-hello-world
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./../../../nodejs-hello-world
  prune: true
  wait: true
  resources:
    - helmrelease.yaml  # Add your HelmRelease resource here
