apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-opentelemetry-demo
  namespace: opentelemetry-demo
spec:
  interval: 5m
  releaseName: opentelemetry-demo
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      version: 0.26.0
  values:
    default:
      envOverrides:
        - name: OTEL_COLLECTOR_NAME
          value: opentelemetry-collector

    opentelemetry-collector:
      enabled: false

    jaeger:
      enabled: false

    prometheus:
      enabled: false

    grafana:
      enabled: false
