apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: production-fixfun
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: custom-store
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: ghcrImagePullSecret
        property: username

    - secretKey: password
      remoteRef:
        key: ghcrImagePullSecret
        property: password
